apiVersion: app/v1
kind: Deployement
metadata:
  name: customer-service
spec:
  replicas: 1
  selector:
    matchLables:
      app: customer-service
template:
  metadata:
    labels:
      app: customer-service

  spec: 
    containers: 
      - name: customer-service
        image:  customer-service
        imagePullPolicy: Never
        ports: 
          - containerPort: 3002
          
---

apiVersion: v1
kind: Service
metadata:
  name: customer-service-srv
spec:
  selector:
    app: customer-service
  ports:
    # - protocol: TCP
      port: 3002
      targetPort: 3002
  #     nodePort: 3099
  # type: NodePort
