apiVersion: app/v1
kind: Deployement
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLables:
      app: inventory-service
template:
  metadata:
    labels:
      app: inventory-service

  spec: 
    containers: 
      - name: inventory-service
        image:  inventory-service
        imagePullPolicy: Never
        ports: 
          - containerPort: 3001
          
---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service-srv
spec:
  selector:
    app: inventory-service
  ports:
    # - protocol: TCP
      port: 3001
      targetPort: 3001
  #     nodePort: 3000
  # type: NodePort
