apiVersion: app/v1
kind: Deployement
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLables:
      app: order-service
template:
  metadata:
    labels:
      app: order-service

  spec: 
    containers: 
      - name: order-service
        image:  order-service
        imagePullPolicy: Never
        ports: 
          - containerPort: 3000
          
---

apiVersion: v1
kind: Service
metadata:
  name: order-service-srv
spec:
  selector:
    app: order-service
  ports:
    # - protocol: TCP
      port: 3000
      targetPort: 3000
  #     nodePort: 3099
  # type: NodePort
  